# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-04 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Article')),
                ('description', models.TextField(verbose_name='Synopsis')),
                ('content', models.TextField(verbose_name='Full description')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2021, 4, 4, 15, 29, 12, 561139), verbose_name='Publicated')),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog post',
                'db_table': 'Posts',
                'ordering': ['-posted'],
            },
        ),
    ]
